LikeLion-FE-React-Project04/project-repo

- package.json
- src/firebase/app.js
- src/index.jsx
초기 환경 세팅
<아직 브랜치 전략이 결정되지 않아서 테스트중>
> Setting 설정

- README.md
- 아래사진과 같이 README.md를 수정하였습니다.
> [test] README.md 내용추가 #31

- public/index.html
- src/styles/main.module.css
- webpack/loaders/styleLoader.js
- webpack/loaders/styleModuleLoader.js
> 🔧 스타일 설정 수정 #43

- package.json
- src/components/ProductCard/ProductCard.jsx
- src/components/ProductCard/ProductCard.module.scss
- 스와이퍼, classNames 패키지 설치
- ProductCard 컴포넌트 생성
> [PR] 패키지 적용을 위한 merge

- src/components/PageTitle/PageTitle.jsx
- src/components/PageTitle/PageTitle.module.scss
> ✨ [feat] 서브페이지 공통 타이틀 컴포넌트 제작 #2

- src/components/FormInput/FormInput.jsx
- src/components/FormInput/FormInput.module.scss
- src/components/index.js
- src/pages/SignIn/SignIn.jsx
> [feat] 로그인 FormInput 공통컴포넌트 #3

- src/pages/SignIn/SignIn.module.scss
> [feat] SignIn.module.scss 파일만 추가 #3

- src/components/FormInput/FormInput.jsx
- src/components/FormInput/FormInput.module.scss
- src/components/PageTitle/PageTitle.jsx
- src/components/PageTitle/PageTitle.module.scss
- src/pages/SignIn/SignIn.jsx
- src/pages/SignIn/SignIn.module.scss
> 🧑 [QUESTION] 컴포넌트 범용성 높이기 #50

- src/components/Button/Button.jsx
- src/components/Button/Button.module.scss
- src/components/FormInput/FormInput.jsx
- src/components/FormInput/FormInput.module.scss
- src/components/index.js
- src/pages/SignIn/SignIn.jsx
- src/pages/SignIn/SignIn.module.scss
> [feat] 폼인풋과 버튼 컴포넌트 완성 #3

- src/components/Button/Button.jsx
- src/pages/SignIn/SignIn.jsx
- src/pages/SignIn/SignIn.module.scss
> [feat] 로그인 마크업 및 css 완성 #3

- src/components/Button/Button.jsx
- src/pages/SignIn/SignIn.jsx
> 🐛 [fix] 버튼 컴포넌트 클릭이벤트가 안되는 문제 해결

- src/components/Counter/Count.jsx
- src/components/Counter/Counter.jsx
- src/components/Counter/Counter.module.scss
- src/components/Counter/CounterBtn.jsx
- src/components/Counter/CounterBtn.module.scss
- src/store/CounterState.js
> [FEATURE] Counter 컴포넌트 개발

- src/components/Button/Button.jsx
- src/components/Button/Button.module.scss
- src/store/cartModalState.js
> [FEATURE] Button 컴포넌트 커스텀 기능추가

- src/components/Button/Button.module.scss
- src/firebase/auth/index.js
- src/firebase/auth/useAuthState.js
- src/firebase/auth/useSignOut.js
- src/pages/SignIn/SignIn.jsx
- src/pages/SignIn/SignIn.module.scss
- 로그인 인증 및 홈 화면 전환
- 로그인 서브타이틀 마진탑 적용
- 로그인 중일 때 버튼 클릭 불가 및 색상 변경
> ✨ [feat] 로그인 인증 및 홈 화면 전환

- src/pages/SignIn/SignIn.jsx
로그인 버튼 2번 클릭 해야 페이지 이동하는 이슈 해결 #82
> 🐛 [fix] 로그인 버튼 2번 클릭 해야 페이지 이동하는 이슈 해결 #82

- src/pages/Home/Home.jsx
- src/pages/Home/Mainmodal/useGetCookieEvent.js
- src/utils/getCookie.js
- src/utils/index.js
> ⚡️ [refactoring] 메인모달관련해서 여러 파일로 분리하기 #11

- src/pages/Home/Home.jsx
- src/pages/Home/Linebanner/Linebanner.jsx
- src/pages/Home/Linebanner/Linebanner.module.scss
- src/pages/Home/Mainmodal/Mainmodal.module.scss
main페이지의 라인 배너 구현 완료했습니다.
PR하겠습니다.
> ✨ [feat] main페이지 라인배너 구현 #9

- src/assets/common/ic-right-arrow.svg
- src/components/RadioButton/RadioButton.jsx
- src/components/RadioButton/RadioButton.module.scss
- src/pages/SignUp/Input.jsx
- src/pages/SignUp/Input.module.scss
- src/pages/SignUp/SignUp.jsx
- src/pages/SignUp/SignUp.module.scss
> ✨ [feat] :  회원가입 컴포넌트 마크업 완성 #2

- src/components/Button/Button.jsx
- src/components/RadioButton/RadioButton.jsx
- src/components/RadioButton/RadioButton.module.scss
- src/pages/SignUp/SignUp.jsx
- src/pages/SignUp/SignUp.module.scss
> 🎨 [modify] 회원가입 라디오 버튼 수정 #2

- src/pages/SignIn/SignIn.module.scss
> ✨ [feat] 로그인 페이지 margin-bottom 스타일 추가

- src/firebase/auth/index.js
- src/firebase/auth/useSignUp.js
- src/firebase/firestrore/index.js
- src/firebase/firestrore/useCreateAuthUser.js
- src/pages/SignUp/SignUp.jsx
**회원가입 로직 구현**
- 비밀번호. 아이디 유효성 검사
- 이메일, 비밀번호, 이름만 입력하면 회원가입 완료
-  **회원가입 후 메인페이지로 이동하도록 해야함**
> ✨ [feat] 회원가입 로직 구현 #2

- src/components/PageTitle/PageTitle.jsx
- src/index.jsx
- src/pages/Home/Home.jsx
- src/pages/Home/Home.module.scss
- src/pages/ProductDetail/ProductDetail.jsx
**홈 페이지 완성**
- 리펙토링 필요 (최적화. 웹접근성)
> [FEATURE] 홈 페이지 완성

- src/components/StorybookExample/Button.jsx
- src/components/StorybookExample/Button.stories.ts
- src/components/StorybookExample/button.css
> ✨ [SETTING] 스토리북 사용법 예시 적용 #104

- src/components/Badge/Badge.jsx
- src/components/Badge/Badge.module.scss
```<Badge uiType='noticeBadge'>공지</Badge>```
```<Badge uiType='bestBadge'>베스트</Badge>```
```<Badge uiType='purpleBadge'>퍼플</Badge>```
> ✨ [feat] 상품후기, 상품문의에 쓰이는 Badge컴포넌트 #96

- src/components/PageTitle/PageTitle.jsx
- src/components/PageTitle/PageTitle.module.scss
- src/pages/SignIn/SignIn.jsx
- src/pages/SignUp/SignUp.jsx
```<PageTitle uiType='productReviewAndInquiry'>상품후기</PageTitle>```
> ✨ [feat] 상품후기, 상품문의  pageTitle 컴포넌트에 추가

- src/assets/main/ic-pause-button.svg
- src/assets/main/ic-play-button.svg
- src/pages/Home/Carousel/MainCarousel.jsx
- src/pages/Home/Carousel/MainCarousel.module.scss
- stop/start, Autoplay, Pagination 기능 추가 #118
> ✨ [feat]MainCarousel

- src/components/ProductDetailPopUp/ProductDetailPopUp.jsx
- src/firebase/firestore/useDetailCollection.js
- src/pages/ProductDetail/ProductInquiry/ProductInquiry.jsx
- 로그인 하지 않은 사용자가 문의/리뷰글을 작성하려고 하면, 로그인한 사용자만 사용할 수 있다고 경고창 띄우기
- 지금은 alert로 띄웠는데(할거 많이 남아서), 나중에 다 구현하고 시간 남으면 모달창으로 변경할수도 있음
- 데이터 최근 등록순으로 정렬하기
> [Feat/#96] 

- src/components/ProductDetailPopUp/ProductDetailPopUp.jsx
- src/components/ProductDetailPopUp/Secret/Secret.jsx
- src/pages/ProductDetail/ProductInquiry/ProductInquiry.jsx
- src/pages/ProductDetail/ProductInquiry/ProductInquiry.module.scss
- src/pages/ProductDetail/ProductInquiry/ProductInquiryAccordion/ProductInquiryAccordion.jsx
- src/pages/ProductDetail/ProductInquiry/ProductInquiryAccordion/ProductInquiryAccordion.module.scss
1. '비밀글입니다' 글자색 검정->회색으로 변경
2. 작성일 뒤에 .없애고, 너비 맞추기
3. 사용자 이름에 *로 이름 가려주기
4. 페이지네이션 (우선적으로 진행할 예정)
> ✨ [feat] 리뷰/문의 팝업창 비밀글 상태/로그인 상태 고려해서 구현 #96 

- src/components/DetailPagination/DetailPagination.jsx
- src/components/DetailPagination/DetailPagination.module.css
- src/pages/ProductDetail/ProductInquiry/@recoil/renderState.js
- src/pages/ProductDetail/ProductInquiry/ProductInquiry.jsx
- src/pages/ProductDetail/ProductInquiry/ProductInquiry.module.scss
- src/pages/ProductDetail/ProductInquiry/ProductInquiryAccordion/ProductInquiryAccordion.jsx
- 단, 공용컴포넌트화 시켜서 적용한건 아님
- 공용 컴포넌트화 (DetailPagination)을 시키려고 했지만, 시간 관계상 우선순위를 뒤로 미뤄둠
> ✨ [feat] 문의 팝업창 페이지네이션 적용 #96

- src/pages/ProductDetail/ProductThumbnail/ProductThumbnail.jsx
- src/pages/ProductDetail/ProductThumbnail/ProductThumbnail.module.scss
> 🎨 [REFACTORIGN ]ProductThumbnail 로직 수정

- src/pages/ProductDetail/ProductReview/ReviewListContainer.jsx
```
{count ? <ProductReviewList data={dataState} /> : <Empty alt='따끈한 첫 후기를 기다리고 있어요.' />}
```
> ✨ [feat] 상품 후기 리스트 비어있을 때 svg에 alt 추가 #98

- src/pages/ProductList/FilterContainer.jsx
- src/pages/ProductList/FilterList.jsx
- src/pages/ProductList/ProductList.jsx
- src/pages/ProductList/SortButton.jsx
> 🔨 [refactor] ProductList 코드 수정 #183

- src/firebase/firestore/useDetailCollection.js
- src/utils/getStarName.js
관련 이슈를 참고하시오.
- https://github.com/LikeLion-FE-React-Project04/project-repo/issues/204
> ✨ [feat] 문의/후기글의 작성자 이름일부를 *로 가리기 #204

- src/components/Button/Button.jsx
- src/components/CartModal/CartModal.jsx
- src/components/Counter/Counter.jsx
- src/components/Counter/CounterBtn.jsx
- src/components/ProductCard/CartButton.jsx
- src/components/ProductCard/CartButton.module.scss
- src/components/ProductCard/ProductCard.jsx
- src/components/ProductCard/ProductCard.module.scss
- src/pages/Home/Carousel/MainCarousel.jsx
- src/pages/Home/Carousel/MainCarousel.module.scss
- src/store/CounterState.js
- src/store/cartModalState.js
1. 컴포넌트 코드 정리
2. Button forwardRef 적용
3. Counter 리팩토링
4. 장바구니 모달 리팩토링
https://github.com/LikeLion-FE-React-Project04/project-repo/issues/206
https://github.com/LikeLion-FE-React-Project04/project-repo/issues/208
> [REFACTORING] 장바구니 모달 웹접근성 리팩토링

- src/pages/ProductDetail/ProductInquiry/ProductInquiry.jsx
- src/pages/ProductDetail/ProductReview/ReviewListContainer.jsx
관련 이슈에서 발견된 버그를 해결했습니다.
- https://github.com/LikeLion-FE-React-Project04/project-repo/issues/207
위의 이슈를 마무리 했다고 생각했는데,
제가 오직 여러페이지가 존재할때만 고려했었습니다.
그래서, 한페이지밖에 존재하지 않을 경우를 고려해서 코드를 수정했습니다.
> 🐛 [fix] 한페이지또는 데이터가 없을때도 고려 #207

- src/pages/ProductDetail/ProductInquiry/ProductInquiry.module.scss
- src/pages/ProductDetail/ProductReview/ReviewListContainer.module.scss
기존 이슈에서 피드백을 받아, 버튼 스타일을 수정했습니다.
- https://github.com/LikeLion-FE-React-Project04/project-repo/issues/207
> 💄 [style] 버튼 스타일 수정 #207

- src/firebase/firestore/useDetailCollection.js
- src/pages/ProductDetail/ProductInquiry/ProductInquiryAccordion/ProductInquiryAccordion.jsx
- src/pages/ProductDetail/ProductReview/ProductReviewList/ProductReviewList.jsx
관련 이슈를 참고하시오.
- https://github.com/LikeLion-FE-React-Project04/project-repo/issues/204
starWriter를 생성하면서, 예상치 못한 버그가 발생했었습니다.
A라는 사용자가 쓴 비밀글은 A는 볼 수 있어야 하는데, A한테도 비밀글로 보이는 문제가 있었습니다.
이를 해결했습니다.
그 이유는, writer와 starWriter를 합쳐서 관리했기 때문입니다.
useDetailCollection.js에서
writer와 starWriter를 분리했더니, 버그가 해결되었습니다.
> 🐛 [fix] 별이름 로직을 구현하다가 생긴 버그 해결 #204

- src/components/DetailPagination/DetailPagination.module.css
- src/pages/ProductList/Pagination.module.css
**배포를 위한 파일 이름 수정**
컨벤션을 잘 지킵시다!
[**이슈참고**](https://github.com/LikeLion-FE-React-Project04/project-repo/issues/221)
> 🐛 [BUGFIX] 컨벤션에 맞게 파일이름 수정 #221

- src/components/DetailPagination/DetailPagination.module.css
- src/pages/Home/Carousel/ProductsCarousel.jsx
- src/pages/ProductList/Pagination.module.css
- console log 제거
- aria-label 추가
> [REFACTORING] 캐로셀 코드 정리 및 접근성 수정

- src/components/ProductDetailPopUp/Secret/Secret.module.scss
관련 이슈의 [STEP6]을 참고하시오.
- https://github.com/LikeLion-FE-React-Project04/project-repo/issues/228
> ✨ [feat] 비밀글로 설정하기에 포커스 가능하게 하기 #228

- src/components/Footer/Footer.jsx
- https://github.com/LikeLion-FE-React-Project04/project-repo/issues/238
- Footer 코드 쪼개기
> 🎨 [modify] 웹 접근성 피드백을 고려해서 수정하기 #238

- src/components/Header/HeaderIcon/HeaderIcon.jsx
- src/components/Header/HeaderLogoContainer/HeaderLogo.jsx
- src/components/Header/HeaderLogoContainer/NewBadge.jsx
- src/components/Header/HeaderNav/CategoryButton.jsx
- src/components/Header/HeaderNav/MainIconList.jsx
- src/components/Header/HeaderNav/SearchForm.jsx
- src/components/Header/Member/MemberList.jsx
- src/components/Header/SearchInput/SearchInput.jsx
- src/components/Header/Topbanner/Topbanner.jsx
- alt 속성의 대체 텍스트 내용 수정
- 제품 이름 명시
- input과 label 연결하기
> ⚡️ [refactoring] Header - 웹 접근성 피드백 내용 수정 #236

- src/components/AlertBox/@hook/useAlertBox.js
- src/pages/ProductDetail/ProductInquiry/ProductInquiry.jsx
- src/pages/ProductDetail/ProductReview/ReviewTitleContainer.jsx
1. 커스텀훅을 담고 있는 폴더명 변경됨
- ```@hook```로 커스텀훅을 담고 있는 폴더명을 변경했으니, 커스텀훅을 import시켰을때의 경로를 변경하길 바람
2. 경고창을 더 간단하게 사용할 수 있게 코드 수정함
- 기존과 다르게 needToMove/needToRemove를 굳이 넘겨주지 않아도 되게 코드를 변경함
- 바뀐 사용설명서에 대해서는 다음 이슈를 참고하시오.
- https://github.com/LikeLion-FE-React-Project04/project-repo/issues/220
3. 성능 최적화
- useMemo를 사용해서 성능최적화를 시켰습니다
- 어떤식으로 성능최적화를 시켰는지는 다음 이슈에 **매우 자세히** 써놓았으니 참고하세요.
- https://github.com/LikeLion-FE-React-Project04/project-repo/issues/220
아마 지금 석원님께서 pull을 받으시면 에러가 날 것 입니다. 
그 이유는, 석원님 파트인
위의 두 파일을 제가 바꾼 형식에 맞게 수정해야 합니다.
**따라서, 맞게 수정하신 후, 반드시 다시 push해주세요.**
> 🎨 [modify] 경로변경 및 성능최적화를 고려해서 useMemo적용 #220

- src/pages/Cart/CartAccordion/CartAccordionPanelItem.jsx
- src/pages/SignUp/@hook/useConfirmEmail.js
- src/pages/SignUp/@hook/useSignUpSubmit.js
https://github.com/LikeLion-FE-React-Project04/project-repo/pull/251 참고
> 🎨 [MODIFY] alertbox 사용 조건에 맞게 코드 수정

- src/hooks/useAddress.jsx
- src/pages/Cart/Address/Address.jsx
- src/pages/SignUp/@hook/useSignUpValidation.js
- src/pages/SignUp/GenderInput/GenderInput.jsx
- src/pages/SignUp/SignUpAddress/SignUpAddress.jsx
- src/utils/checkValidation.js
https://github.com/LikeLion-FE-React-Project04/project-repo/issues/248 참고
> [BUGFIX] 회원가입 버그 수정

- src/components/Counter/CounterBtn.module.scss
디테일한 부분 CSS 간단 수정
- https://github.com/LikeLion-FE-React-Project04/project-repo/issues/243
> 💄 [style] 비활성화/활성화 상태일 때 cursor모양 다르게 하기 #243

- src/pages/ProductDetail/ProductDetail.jsx
> ✨ [feat] 네비게이션바의 후기탭에 현재 후기의 개수가 업데이트 #225

- src/pages/ProductDetail/ProductDetail.jsx
네비게이션바에서 후기탭에 후기 개수를 세는 기능을 추가하면서,
기존의 코드와 겹쳐서 문제가 생겼습니다.
그점을 해결했습니다.
> 🐛 [fix] 코드 충돌로 인한 오류 해결 #225

- src/pages/ProductDetail/ProductDetailMenu/ProductDetailMenu.module.scss
> ✨ [feat] 스크롤 내릴 시 헤더 아래로 위치 고정 #225

- src/pages/ProductDetail/ProductDetail.jsx
- src/pages/ProductDetail/ProductDetailMenu/ProductDetailMenu.jsx
- src/pages/ProductDetail/ProductDetailMenu/ProductDetailMenu.module.scss
- src/pages/ProductDetail/ProductInquiry/ProductInquiry.module.scss
- src/pages/ProductDetail/ProductReview/ProductReview.module.scss
- 스크롤에 따른 style 변화를 줄 때, 코드가 너무 비효율적이라고 판단
- 가끔 에러가 발생함
에러메세지 내용은 다음과 같습니다.
Cannot read properties of null (reading 'getBoundingClientRect')
> ✨ [feat] 스크롤 이동에 따른 버튼 스타일 변화 #225

- src/pages/ProductDetail/ProductDetail.jsx
- src/pages/ProductDetail/ProductDetailMenu/ProductDetailMenu.jsx
> 🎨 [REFACTORING] 네비게이션 스크롤 이벤트 리팩토링 #225

- src/pages/ProductDetail/ProductDetail.jsx
> 🎨 [modify] setPosition설정 범위 변화 #225

- src/components/CartPopup/CartPopup.jsx
- src/components/CartPopup/CartPopup.module.scss
- src/components/Header/HeaderIcon/HeaderIcon.jsx
- src/components/Header/HeaderNav/MainIconList.jsx
- src/pages/Layout/Layout.jsx
- https://github.com/LikeLion-FE-React-Project04/project-repo/issues/210
> 🐛 [BUGFIX] 장바구니 알림 팝업 위치 버그 수정 #210

- src/components/ProductCard/CartButton.jsx
- src/components/ProductCard/ProductCard.jsx
- src/pages/Home/Carousel/MainCarousel.jsx
- src/pages/Home/Carousel/MainCarousel.module.scss
- src/pages/Home/Carousel/ProductsCarousel.jsx
- src/pages/Home/Carousel/ProductsCarousel.module.scss
- src/pages/Layout/Layout.jsx
- src/pages/Layout/Layout.module.scss
- src/styles/_base.css
- https://github.com/LikeLion-FE-React-Project04/project-repo/issues/292 참고
> Refactoring/#292 캐로셀 웹접근성 수정

- package.json
- src/components/CartPopup/CartPopup.jsx
- src/components/CartPopup/CartPopup.module.scss
- https://github.com/LikeLion-FE-React-Project04/project-repo/issues/296 참고
> Refactoring/#296 장바구니 알림 팝업창 리팩토링

- src/pages/ProductDetail/ProductDetailMenu/ProductDetailMenu.module.scss
관련 이슈 참고
- https://github.com/LikeLion-FE-React-Project04/project-repo/issues/300
> 🐛 [fix] 디테일페이지의 네비게이션바 버튼 포커스 스타일 관련 버그 #300

- src/pages/ProductDetail/DetailInformation/DetailInformation.jsx
- src/pages/ProductDetail/ProductDetail.jsx
- src/pages/ProductDetail/ProductInformation/ProductInformation.jsx
- src/pages/ProductDetail/ProductThumbnail/ProductThumbnail.jsx
- src/pages/SignUp/@hook/useSignUpSubmit.js
> Refactoring 2/#225 네비게이션 수정

- src/components/ProductDetailPopUp/ProductDetailPopUp.jsx
- src/firebase/firestore/useDetailCollection.js
- src/firebase/firestore/useDetailFireStore.js
- src/pages/ProductDetail/ProductInquiry/ProductInquiry.jsx
- https://github.com/LikeLion-FE-React-Project04/project-repo/issues/305
- https://github.com/LikeLion-FE-React-Project04/project-repo/issues/304
- https://github.com/LikeLion-FE-React-Project04/project-repo/issues/303
> 불필요한 코드 정리
